server:
  port: 8001
spring:
  main:
    allow-circular-references: true
  application:
    name: springcloud-consumer

# eureka 配置
eureka:
  client:
    serviceUrl:
      defaultZone: http://jorian:123456@localhost:8761/eureka
logging:
  level:
    root: INFO